# Generated by Django 4.2.15 on 2024-10-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewsters_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
    ]
